name: Deploy Sylas Front to VPS

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET 8
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 8.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Build (Release)
              run: dotnet build --configuration Release --no-restore

            - name: Publish
              run: dotnet publish --configuration Release --output ./publish --no-restore

            - name: Clean remote directory via SSH
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  script: rm -rf /home/jikai/sylas/*

            - name: Deploy
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  port: 22
                  source: 'dist/sylas-front/browser/*'
                  target: '/home/jikai/sylas'
                  strip_components: 3

            - name: Restart sylas service via SSH
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  script: sudo systemctl restart sylas-api.service